# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=200, null=True, verbose_name='Nombre')),
                ('document', models.CharField(db_column='document', max_length=50, null=True, verbose_name='Documento')),
                ('Address', models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Dirrecion')),
                ('trade', models.CharField(db_column='trade', max_length=200, null=True, verbose_name='Negocio')),
                ('loan', models.CharField(db_column='loan', max_length=100, null=True, verbose_name='Prestamo')),
                ('percent', models.CharField(db_column='percent', max_length=50, null=True, verbose_name='Porcentaje')),
                ('payment_days', models.CharField(db_column='payment_days', max_length=50, null=True, verbose_name='Dias a pagar')),
            ],
        ),
        migrations.CreateModel(
            name='informacion_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt', models.CharField(db_column='total_debt', max_length=100, null=True, verbose_name='Deuda total')),
                ('date', models.CharField(db_column='date', max_length=100, null=True, verbose_name='Fecha')),
                ('total_customers', models.CharField(db_column='total_customers', max_length=100, null=True, verbose_name='Total clientes')),
                ('total_collect_day', models.CharField(db_column='total_collect_day', max_length=100, null=True, verbose_name='Total recaudado en el dia')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(db_column='document', max_length=50, null=True, verbose_name='Documento')),
                ('date', models.CharField(db_column='date', max_length=100, null=True, verbose_name='Fecha')),
                ('payment', models.CharField(db_column='payment', max_length=100, null=True, verbose_name='Abono')),
                ('total_days', models.CharField(db_column='Total_days', max_length=50, null=True, verbose_name='Total dias')),
                ('total_payment', models.CharField(db_column='total_payment', max_length=50, null=True, verbose_name='Total a pagar')),
                ('delayed_days', models.CharField(db_column='delayed_days', max_length=50, null=True, verbose_name='Dias atrasado')),
            ],
        ),
    ]
