# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.CharField(db_column='customers', max_length=200, null=True, verbose_name='Usuario')),
                ('password', models.CharField(db_column='password', max_length=200, null=True, verbose_name='Contrasena')),
            ],
        ),
    ]
