# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0002_login_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_admin',
            name='login',
            field=models.CharField(choices=[(True, 'SI'), (False, 'NO')], db_column='login', default=False, max_length=10, null=True, verbose_name='Logeo'),
        ),
    ]
