# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0004_auto_20160224_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdelta.datos_cliente'),
        ),
    ]
