# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0005_auto_20160224_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_admin',
            name='name',
            field=models.CharField(db_column='name', max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
