# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0006_login_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='phone',
            field=models.CharField(db_column='phone', max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='Address',
            field=models.CharField(db_column='Address', max_length=200, null=True, verbose_name='Direcion'),
        ),
    ]
