# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0007_auto_20160226_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdelta.datos_cliente', verbose_name='Documento'),
        ),
    ]
