# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0010_auto_20160303_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo_cliente',
            old_name='document',
            new_name='documen',
        ),
    ]
