# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0012_datos_cliente_total_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_cliente',
            name='total_payment',
        ),
    ]
