# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0013_remove_datos_cliente_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='total_payment',
            field=models.CharField(db_column='total_payment', max_length=50, null=True, verbose_name='Total a pagar'),
        ),
    ]
