# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0014_datos_cliente_total_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='deuda_actual',
            field=models.CharField(db_column='deuda_actual', max_length=50, null=True, verbose_name='Deuda actual'),
        ),
    ]
