# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0015_datos_cliente_deuda_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cliente',
            name='deuda_actual',
            field=models.IntegerField(db_column='deuda_actual', max_length=50, null=True, verbose_name='Deuda actual'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='loan',
            field=models.IntegerField(db_column='loan', max_length=100, null=True, verbose_name='Prestamo'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='percent',
            field=models.IntegerField(db_column='percent', max_length=50, null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='total_payment',
            field=models.IntegerField(db_column='total_payment', max_length=50, null=True, verbose_name='Total a pagar'),
        ),
    ]
