# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0016_auto_20160303_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_cliente',
            name='deuda_actual',
        ),
        migrations.AddField(
            model_name='prestamo_cliente',
            name='deuda_actual',
            field=models.IntegerField(db_column='deuda_actual', max_length=50, null=True, verbose_name='Deuda actual'),
        ),
        migrations.AddField(
            model_name='prestamo_cliente',
            name='sumado',
            field=models.CharField(db_column='sumado', max_length=100, null=True, verbose_name='Sumado'),
        ),
    ]
