# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0017_auto_20160304_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cliente',
            name='loan',
            field=models.IntegerField(db_column='loan', null=True, verbose_name='Prestamo'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='percent',
            field=models.IntegerField(db_column='percent', null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='total_payment',
            field=models.IntegerField(db_column='total_payment', null=True, verbose_name='Total a pagar'),
        ),
        migrations.AlterField(
            model_name='datos_cliente',
            name='trade',
            field=models.CharField(db_column='trade', max_length=50, null=True, verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='deuda_actual',
            field=models.IntegerField(db_column='deuda_actual', null=True, verbose_name='Deuda actual'),
        ),
    ]
