# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0018_auto_20160304_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='sumado',
            field=models.IntegerField(db_column='sumado', max_length=100, null=True, verbose_name='Sumado'),
        ),
    ]
