# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0021_auto_20160304_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='deuda_actual',
            field=models.IntegerField(db_column='deuda_actual', null=True, verbose_name='Deuda actual'),
        ),
        migrations.AddField(
            model_name='datos_cliente',
            name='payment',
            field=models.CharField(db_column='payment', max_length=100, null=True, verbose_name='Abono'),
        ),
    ]
