# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0022_auto_20160304_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo_cliente',
            name='delayed_days',
        ),
        migrations.RemoveField(
            model_name='prestamo_cliente',
            name='total_days',
        ),
        migrations.AddField(
            model_name='prestamo_cliente',
            name='payment_total',
            field=models.CharField(db_column='payment_total', max_length=100, null=True, verbose_name='Abonado total'),
        ),
    ]
