# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0024_remove_datos_cliente_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='total_payment',
            field=models.IntegerField(db_column='total_payment', null=True, verbose_name='Total a pagar'),
        ),
    ]
