# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0025_auto_20160304_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='payment',
            field=models.IntegerField(db_column='payment', null=True, verbose_name='Abono'),
        ),
        migrations.AlterField(
            model_name='prestamo_cliente',
            name='payment_total',
            field=models.IntegerField(db_column='payment_total', null=True, verbose_name='Abonado total'),
        ),
    ]
