# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0026_auto_20160304_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='total_abonado',
            field=models.IntegerField(db_column='total_abonado', null=True, verbose_name='Total abonado'),
        ),
    ]
