# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0027_datos_cliente_total_abonado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo_cliente',
            name='payment_total',
        ),
    ]
