# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0029_prestamo_cliente_total_abonado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_admin',
            name='login',
        ),
    ]
