# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0030_remove_login_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_admin',
            name='permisos',
            field=models.IntegerField(db_column='permisos', null=True, verbose_name='Permisos'),
        ),
    ]
