# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0031_login_admin_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_admin',
            name='cargo',
            field=models.IntegerField(db_column='cargo', null=True, verbose_name='Cargo'),
        ),
    ]
