# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0032_login_admin_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_admin',
            name='cargo',
            field=models.CharField(db_column='cargo', max_length=200, null=True, verbose_name='Cargo'),
        ),
    ]
