# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0034_login_admin_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo_cliente',
            name='hour',
            field=models.CharField(db_column='hour', max_length=100, null=True, verbose_name='Hora'),
        ),
    ]
