# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0036_datos_cliente_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_cliente',
            name='deuda_actual',
        ),
        migrations.AddField(
            model_name='datos_cliente',
            name='presmaspor',
            field=models.IntegerField(db_column='presmaspor', null=True, verbose_name='Prestamos mas porcentaje'),
        ),
    ]
