# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0036_datos_cliente_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacion_diaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_column='date', max_length=100, null=True, verbose_name='Fecha')),
                ('abono_diario', models.CharField(db_column='abono_diario', max_length=200, null=True, verbose_name='Abono diario')),
            ],
        ),
        migrations.RemoveField(
            model_name='datos_cliente',
            name='deuda_actual',
        ),
        migrations.AddField(
            model_name='datos_cliente',
            name='presmaspor',
            field=models.IntegerField(db_column='presmaspor', null=True, verbose_name='Prestamos mas porcentaje'),
        ),
    ]
