# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0037_auto_20160311_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo_cliente',
            name='total_abonado_dia',
            field=models.IntegerField(db_column='total_abonado_dia', null=True, verbose_name='Total abonado dia'),
        ),
    ]
