# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0038_prestamo_cliente_total_abonado_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_cliente',
            name='dateprestamo',
            field=models.CharField(db_column='dateprestamo', max_length=100, null=True, verbose_name='Fecha prestamo'),
        ),
    ]
