# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0039_datos_cliente_dateprestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cliente',
            name='dateprestamo',
            field=models.CharField(db_column='dateprestamo', max_length=100, null=True, verbose_name='Fecha del prestamo'),
        ),
    ]
