# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdelta', '0042_auto_20160315_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_cliente',
            name='payment_days',
            field=models.IntegerField(db_column='payment_days', null=True, verbose_name='Dias a pagar'),
        ),
    ]
